### ISSUE TITLE
Monoprop is not returned upon boarding.

### ISSUE THREAD

**Issue by c-lipka** [linuxgurugamer/EvaFuel#14]
I always get "0 units of monopropellant returned" when boarding after an EVA, even if the Kerbal never even touched their jet pack.

Using KSP 1.8.1 with Kerbalism, in case that makes any difference (plus a couple of other mods that I don't expect to be involved in any way).

**Comment by linuxgurugamer** [comment]
I believe that Kerbalism does it's own thing.  I don't support Kerbalism, sorry
Also, you should post in the forums before here, because that way other people can also help and answer questions.  You might even find the answer to a question before you post.
