### ISSUE TITLE
Monopropellant is spent, but not transferred after 1.3

### ISSUE THREAD

**Issue by MuhsinFatih** [linuxgurugamer/EvaFuel#5]
I enabled the fuel transfer message, when I go for EVA it says 5 units of EVA propellant is transferred to the kerbal. 5 units of monopropellant is removed from the ship, but Jebediah (or any other kerbal :P) has no monopropellant. When jeb gets back into ship he returns no monopropellant. Which 1: leaves kerbals stranded if let go of the ladder, 2: Wastes monopropellant

**Comment by MuhsinFatih** [comment]
Well strangely enough, after disabling EvaFuel I am still unable to use RCS on EVA. Perhaps the issue is not with this mod. Sorry

**Comment by MuhsinFatih** [comment]
Yeah as I said, sorry I didn't know about the incompatibility you mentioned in the forum post. Turns out after deleting kerbalism dll, the old kerbalism files I kept for keeping my ships with kerbalism parts alive were interfering with the game. Removed everything in kerbalism folder except parts solved the problem

**Comment by linuxgurugamer** [comment]
No problem, thanks for getting back to me
