### ISSUE TITLE
cant use eva-11 fuel canister from KIS to refill krbal eva fuel

### ISSUE THREAD

**Issue by danielboro** [linuxgurugamer/EvaFuel#9]
i tried to use a eva fuel canister(the extra EVA fuel tank from kis) to refile my kerbal eva fuel
it didnt work.

logs for KSP 1.3.1 incloding a save file
the clip: https://yadi.sk/d/UILtrqH93PKepr
logs https://www.dropbox.com/sh/8egnwnm1cg49cl2/AAAjQtHrx9IgkEA_wu4M4bYSa?dl=0
 6 logs: 3 ksp.log and 3 output_log

kis + 1.6 evafuel- cant refuel (-eftest)
kis - can refule (-eftest2)
kis+1.6.1 evafue- cant refuel (-newef)
i included persistent and quicksave
jeb  is in epod bosted and he has 2 eve-11 kis refuel canisters

the ship is stock+MJ

 

complit mod list for file
KSP: 1.3.1 (Win64) - Unity: 5.4.0p4 - OS: Windows 10  (10.0.0) 64bit
Toolbar - 1.7.15
UI Core - 1.0
Action Group Manager - 2.2.1
Community Category Kit - 2.0.2
Community Trait Icons - 0.1.2
EVAFuelContinued - 1.6.1
Flight Plan - 1.0.4
Kerbal Engineer Redux - 1.1.3
HyperEdit - 1.5.4
Kerbal Inventory System - 1.7.6468.41490
kOS - 1.1.3.2
KSP-AVC Plugin - 1.1.6.2
EVAParachutesAndEjectionSeats - 0.1.15
IVA Kerbal Identifier - 1.0.4 

log from KSP 1.3.0 using evafuel vesrion 1.5
 https://yadi.sk/d/DfUYkBey3NBTJv
https://yadi.sk/d/jpeFicBX3NBTLU

**Comment by linuxgurugamer** [comment]
I know this is old, but could you update it with either KSP 1.7.3 or KSP 1.8?  Use the appropriate version of the mod
Thanks

**Comment by danielboro** [comment]
works on lunch pad
tested in 1.7.3 
KIS 1.22
EVAFuel Continued 1.6.6.2
new install, no settings customization.
extra mods
CC,KAS,KER,MM,MJ

ill test in 1.7.0 later
my main game was not updates yet
planing to go to 1.8 wen inaf mods are updated

**Comment by linuxgurugamer** [comment]
Ok, so if it's working in 1.7.3, then I suppose the problem was fixed.
I'm closing this, if it happens again in 1.8, just open a new ticket

**Comment by powerboat9** [comment]
I'm having a similar issue. I can't refuel my kerbals using the EVA-11 fuel canister either.

**Comment by linuxgurugamer** [comment]
> I'm having a similar issue. I can't refuel my kerbals using the EVA-11 fuel canister either.

did  you read the whole thread?  Didn't I say open a NEW ticket?

Also, just saying that something is broken without any other information is very useless.  For example, what version of KSP are you playing?  How about a log file?  I could go on, but I think you get the point.
Finally, posting in the KSP Forums in the thread for this mod is usually better, in that if there is a known answer, others besides myself can answer you
